# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 894348c0b0749eaffdeabbed0dd523c1c76c84d45ebee48bb6dc2b5e7baba0688facd7343c789d0867f0eb749754f25fa7d60dfef5b41939590437d07407f22a
  mailgun_api_key: <%= ENV["MAILGUN_APIKEY"] %>
  email_whitelist: <%= ENV['EMAIL_WHITELIST'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  s3_bucket_name: <%= ENV['S3_BUCKET_NAME'] %>

test:
  secret_key_base: 86cd8ffc05b20cd02e944088a13da3dc30db20079d0cd6a394a86e7cf17116fbecd06ed713b951617e7c4543ae0426c2df5804422963226dd3facb5172832ade
  mailgun_api_key: key-3760e2f8c5971a69fb1fce0bf3cc209e1
  email_whitelist:
  aws_access_key_id:
  aws_secret_access_key:
  s3_bucket_name: photogun-testing

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailgun_api_key: <%= ENV["MAILGUN_APIKEY"] %>
  email_whitelist: <%= ENV['EMAIL_WHITELIST'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  s3_bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
